language: "ja-JP"
early_access: true
reviews:
  profile: "assertive"
  auto_title_instructions: Simple/Clear
  auto_apply_labels: true
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  in_progress_fortune: true
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!src/definition/**"
    - "!test/cppcheck_report.xml"
    - "!test/coverage_report.json"
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
      - "main-pre"
chat:
  auto_reply: true
  art: true