#pragma once
// AUTO-GENERATED from azarashi 0.16.1 with CI-CD
// Source module : qzss_dcr_jma_epicenter_and_hypocenter
// Variable      : qzss_dcr_jma_epicenter_and_hypocenter
// Entries       : 345
// Strategy      : binary_search

// NOTE: This function may return nullptr for unknown IDs.
// Callers MUST perform a null-check before using the result.

#include <cstdint>
#include <optional>
#include <string_view>
#include "../azaraC.h"

namespace azaraC {
namespace def {

#if (AZARAC_ENABLE_EEW || AZARAC_ENABLE_HYPOCENTER)

struct QZSS_DCR_JMA_EPICENTER_AND_HYPOCENTER_Entry { uint16_t id; std::optional<std::string_view> label; };
inline constexpr QZSS_DCR_JMA_EPICENTER_AND_HYPOCENTER_Entry QZSS_DCR_JMA_EPICENTER_AND_HYPOCENTER_TABLE[] = {
    {0u, std::string_view{"未設定(北西太平洋津波情報)", 14}},
    {11u, std::string_view{"北海道地方", 5}},
    {12u, std::string_view{"東北地方", 4}},
    {13u, std::string_view{"北陸地方", 4}},
    {14u, std::string_view{"関東甲信地方", 6}},
    {15u, std::string_view{"小笠原地方", 5}},
    {16u, std::string_view{"東海地方", 4}},
    {17u, std::string_view{"近畿地方", 4}},
    {18u, std::string_view{"中国地方", 4}},
    {19u, std::string_view{"四国地方", 4}},
    {20u, std::string_view{"九州地方", 4}},
    {21u, std::string_view{"沖縄地方", 4}},
    {100u, std::string_view{"石狩地方北部", 6}},
    {101u, std::string_view{"石狩地方中部", 6}},
    {102u, std::string_view{"石狩地方南部", 6}},
    {105u, std::string_view{"渡島地方北部", 6}},
    {106u, std::string_view{"渡島地方東部", 6}},
    {107u, std::string_view{"渡島地方西部", 6}},
    {110u, std::string_view{"檜山地方", 4}},
    {115u, std::string_view{"後志地方北部", 6}},
    {116u, std::string_view{"後志地方東部", 6}},
    {117u, std::string_view{"後志地方西部", 6}},
    {120u, std::string_view{"空知地方北部", 6}},
    {121u, std::string_view{"空知地方中部", 6}},
    {122u, std::string_view{"空知地方南部", 6}},
    {125u, std::string_view{"上川地方北部", 6}},
    {126u, std::string_view{"上川地方中部", 6}},
    {127u, std::string_view{"上川地方南部", 6}},
    {130u, std::string_view{"留萌地方中北部", 7}},
    {131u, std::string_view{"留萌地方南部", 6}},
    {135u, std::string_view{"宗谷地方北部", 6}},
    {136u, std::string_view{"宗谷地方南部", 6}},
    {140u, std::string_view{"網走地方", 4}},
    {141u, std::string_view{"北見地方", 4}},
    {142u, std::string_view{"紋別地方", 4}},
    {145u, std::string_view{"胆振地方西部", 6}},
    {146u, std::string_view{"胆振地方中東部", 7}},
    {150u, std::string_view{"日高地方西部", 6}},
    {151u, std::string_view{"日高地方中部", 6}},
    {152u, std::string_view{"日高地方東部", 6}},
    {155u, std::string_view{"十勝地方北部", 6}},
    {156u, std::string_view{"十勝地方中部", 6}},
    {157u, std::string_view{"十勝地方南部", 6}},
    {160u, std::string_view{"釧路地方北部", 6}},
    {161u, std::string_view{"釧路地方中南部", 7}},
    {165u, std::string_view{"根室地方北部", 6}},
    {166u, std::string_view{"根室地方中部", 6}},
    {167u, std::string_view{"根室地方南部", 6}},
    {180u, std::string_view{"北海道南西沖", 6}},
    {181u, std::string_view{"北海道西方沖", 6}},
    {182u, std::string_view{"石狩湾", 3}},
    {183u, std::string_view{"北海道北西沖", 6}},
    {184u, std::string_view{"宗谷海峡", 4}},
    {186u, std::string_view{"国後島付近", 5}},
    {187u, std::string_view{"択捉島付近", 5}},
    {188u, std::string_view{"北海道東方沖", 6}},
    {189u, std::string_view{"根室半島南東沖", 7}},
    {190u, std::string_view{"釧路沖", 3}},
    {191u, std::string_view{"十勝沖", 3}},
    {192u, std::string_view{"浦河沖", 3}},
    {193u, std::string_view{"苫小牧沖", 4}},
    {194u, std::string_view{"内浦湾", 3}},
    {195u, std::string_view{"宗谷東方沖", 5}},
    {196u, std::string_view{"網走沖", 3}},
    {197u, std::string_view{"択捉島南東沖", 6}},
    {200u, std::string_view{"青森県津軽北部", 7}},
    {201u, std::string_view{"青森県津軽南部", 7}},
    {202u, std::string_view{"青森県三八上北地方", 9}},
    {203u, std::string_view{"青森県下北地方", 7}},
    {210u, std::string_view{"岩手県沿岸北部", 7}},
    {211u, std::string_view{"岩手県沿岸南部", 7}},
    {212u, std::string_view{"岩手県内陸北部", 7}},
    {213u, std::string_view{"岩手県内陸南部", 7}},
    {220u, std::string_view{"宮城県北部", 5}},
    {221u, std::string_view{"宮城県南部", 5}},
    {222u, std::string_view{"宮城県中部", 5}},
    {230u, std::string_view{"秋田県沿岸北部", 7}},
    {231u, std::string_view{"秋田県沿岸南部", 7}},
    {232u, std::string_view{"秋田県内陸北部", 7}},
    {233u, std::string_view{"秋田県内陸南部", 7}},
    {240u, std::string_view{"山形県庄内地方", 7}},
    {241u, std::string_view{"山形県最上地方", 7}},
    {242u, std::string_view{"山形県村山地方", 7}},
    {243u, std::string_view{"山形県置賜地方", 7}},
    {250u, std::string_view{"福島県中通り", 6}},
    {251u, std::string_view{"福島県浜通り", 6}},
    {252u, std::string_view{"福島県会津", 5}},
    {280u, std::string_view{"津軽海峡", 4}},
    {281u, std::string_view{"山形県沖", 4}},
    {282u, std::string_view{"秋田県沖", 4}},
    {283u, std::string_view{"青森県西方沖", 6}},
    {284u, std::string_view{"陸奥湾", 3}},
    {285u, std::string_view{"青森県東方沖", 6}},
    {286u, std::string_view{"岩手県沖", 4}},
    {287u, std::string_view{"宮城県沖", 4}},
    {288u, std::string_view{"三陸沖", 3}},
    {289u, std::string_view{"福島県沖", 4}},
    {300u, std::string_view{"茨城県北部", 5}},
    {301u, std::string_view{"茨城県南部", 5}},
    {309u, std::string_view{"千葉県南東沖", 6}},
    {310u, std::string_view{"栃木県北部", 5}},
    {311u, std::string_view{"栃木県南部", 5}},
    {320u, std::string_view{"群馬県北部", 5}},
    {321u, std::string_view{"群馬県南部", 5}},
    {330u, std::string_view{"埼玉県北部", 5}},
    {331u, std::string_view{"埼玉県南部", 5}},
    {332u, std::string_view{"埼玉県秩父地方", 7}},
    {340u, std::string_view{"千葉県北東部", 6}},
    {341u, std::string_view{"千葉県北西部", 6}},
    {342u, std::string_view{"千葉県南部", 5}},
    {349u, std::string_view{"房総半島南方沖", 7}},
    {350u, std::string_view{"東京都２３区", 6}},
    {351u, std::string_view{"東京都多摩東部", 7}},
    {352u, std::string_view{"東京都多摩西部", 7}},
    {360u, std::string_view{"神奈川県東部", 6}},
    {361u, std::string_view{"神奈川県西部", 6}},
    {370u, std::string_view{"新潟県上越地方", 7}},
    {371u, std::string_view{"新潟県中越地方", 7}},
    {372u, std::string_view{"新潟県下越地方", 7}},
    {378u, std::string_view{"新潟県下越沖", 6}},
    {379u, std::string_view{"新潟県上中越沖", 7}},
    {380u, std::string_view{"富山県東部", 5}},
    {381u, std::string_view{"富山県西部", 5}},
    {390u, std::string_view{"石川県能登地方", 7}},
    {391u, std::string_view{"石川県加賀地方", 7}},
    {400u, std::string_view{"福井県嶺北", 5}},
    {401u, std::string_view{"福井県嶺南", 5}},
    {411u, std::string_view{"山梨県中・西部", 7}},
    {412u, std::string_view{"山梨県東部・富士五湖", 10}},
    {420u, std::string_view{"長野県北部", 5}},
    {421u, std::string_view{"長野県中部", 5}},
    {422u, std::string_view{"長野県南部", 5}},
    {430u, std::string_view{"岐阜県飛騨地方", 7}},
    {431u, std::string_view{"岐阜県美濃東部", 7}},
    {432u, std::string_view{"岐阜県美濃中西部", 8}},
    {440u, std::string_view{"静岡県伊豆地方", 7}},
    {441u, std::string_view{"静岡県東部", 5}},
    {442u, std::string_view{"静岡県中部", 5}},
    {443u, std::string_view{"静岡県西部", 5}},
    {450u, std::string_view{"愛知県東部", 5}},
    {451u, std::string_view{"愛知県西部", 5}},
    {460u, std::string_view{"三重県北部", 5}},
    {461u, std::string_view{"三重県中部", 5}},
    {462u, std::string_view{"三重県南部", 5}},
    {469u, std::string_view{"三重県南東沖", 6}},
    {471u, std::string_view{"茨城県沖", 4}},
    {472u, std::string_view{"関東東方沖", 5}},
    {473u, std::string_view{"千葉県東方沖", 6}},
    {475u, std::string_view{"八丈島東方沖", 6}},
    {476u, std::string_view{"八丈島近海", 5}},
    {477u, std::string_view{"東京湾", 3}},
    {478u, std::string_view{"相模湾", 3}},
    {480u, std::string_view{"伊豆大島近海", 6}},
    {481u, std::string_view{"伊豆半島東方沖", 7}},
    {482u, std::string_view{"三宅島近海", 5}},
    {483u, std::string_view{"新島・神津島近海", 8}},
    {485u, std::string_view{"駿河湾", 3}},
    {486u, std::string_view{"駿河湾南方沖", 6}},
    {487u, std::string_view{"遠州灘", 3}},
    {489u, std::string_view{"三河湾", 3}},
    {490u, std::string_view{"伊勢湾", 3}},
    {492u, std::string_view{"若狭湾", 3}},
    {493u, std::string_view{"福井県沖", 4}},
    {494u, std::string_view{"石川県西方沖", 6}},
    {495u, std::string_view{"能登半島沖", 5}},
    {497u, std::string_view{"富山湾", 3}},
    {498u, std::string_view{"佐渡付近", 4}},
    {499u, std::string_view{"東海道南方沖", 6}},
    {500u, std::string_view{"滋賀県北部", 5}},
    {501u, std::string_view{"滋賀県南部", 5}},
    {510u, std::string_view{"京都府北部", 5}},
    {511u, std::string_view{"京都府南部", 5}},
    {520u, std::string_view{"大阪府北部", 5}},
    {521u, std::string_view{"大阪府南部", 5}},
    {530u, std::string_view{"兵庫県北部", 5}},
    {531u, std::string_view{"兵庫県南東部", 6}},
    {532u, std::string_view{"兵庫県南西部", 6}},
    {540u, std::string_view{"奈良県", 3}},
    {550u, std::string_view{"和歌山県北部", 6}},
    {551u, std::string_view{"和歌山県南部", 6}},
    {560u, std::string_view{"鳥取県東部", 5}},
    {562u, std::string_view{"鳥取県中部", 5}},
    {563u, std::string_view{"鳥取県西部", 5}},
    {570u, std::string_view{"島根県東部", 5}},
    {571u, std::string_view{"島根県西部", 5}},
    {580u, std::string_view{"岡山県北部", 5}},
    {581u, std::string_view{"岡山県南部", 5}},
    {590u, std::string_view{"広島県北部", 5}},
    {591u, std::string_view{"広島県南東部", 6}},
    {592u, std::string_view{"広島県南西部", 6}},
    {600u, std::string_view{"徳島県北部", 5}},
    {601u, std::string_view{"徳島県南部", 5}},
    {610u, std::string_view{"香川県東部", 5}},
    {611u, std::string_view{"香川県西部", 5}},
    {620u, std::string_view{"愛媛県東予", 5}},
    {621u, std::string_view{"愛媛県中予", 5}},
    {622u, std::string_view{"愛媛県南予", 5}},
    {630u, std::string_view{"高知県東部", 5}},
    {631u, std::string_view{"高知県中部", 5}},
    {632u, std::string_view{"高知県西部", 5}},
    {673u, std::string_view{"土佐湾", 3}},
    {674u, std::string_view{"紀伊水道", 4}},
    {675u, std::string_view{"大阪湾", 3}},
    {676u, std::string_view{"播磨灘", 3}},
    {677u, std::string_view{"瀬戸内海中部", 6}},
    {678u, std::string_view{"安芸灘", 3}},
    {679u, std::string_view{"周防灘", 3}},
    {680u, std::string_view{"伊予灘", 3}},
    {681u, std::string_view{"豊後水道", 4}},
    {682u, std::string_view{"山口県北西沖", 6}},
    {683u, std::string_view{"島根県沖", 4}},
    {684u, std::string_view{"鳥取県沖", 4}},
    {685u, std::string_view{"隠岐島近海", 5}},
    {686u, std::string_view{"兵庫県北方沖", 6}},
    {687u, std::string_view{"京都府沖", 4}},
    {688u, std::string_view{"淡路島付近", 5}},
    {689u, std::string_view{"和歌山県南方沖", 7}},
    {700u, std::string_view{"山口県北部", 5}},
    {702u, std::string_view{"山口県西部", 5}},
    {703u, std::string_view{"山口県東部", 5}},
    {704u, std::string_view{"山口県中部", 5}},
    {710u, std::string_view{"福岡県福岡地方", 7}},
    {711u, std::string_view{"福岡県北九州地方", 8}},
    {712u, std::string_view{"福岡県筑豊地方", 7}},
    {713u, std::string_view{"福岡県筑後地方", 7}},
    {720u, std::string_view{"佐賀県北部", 5}},
    {721u, std::string_view{"佐賀県南部", 5}},
    {730u, std::string_view{"長崎県北部", 5}},
    {731u, std::string_view{"長崎県南西部", 6}},
    {732u, std::string_view{"長崎県島原半島", 7}},
    {740u, std::string_view{"熊本県阿蘇地方", 7}},
    {741u, std::string_view{"熊本県熊本地方", 7}},
    {742u, std::string_view{"熊本県球磨地方", 7}},
    {743u, std::string_view{"熊本県天草・芦北地方", 10}},
    {750u, std::string_view{"大分県北部", 5}},
    {751u, std::string_view{"大分県中部", 5}},
    {752u, std::string_view{"大分県南部", 5}},
    {753u, std::string_view{"大分県西部", 5}},
    {760u, std::string_view{"宮崎県北部平野部", 8}},
    {761u, std::string_view{"宮崎県北部山沿い", 8}},
    {762u, std::string_view{"宮崎県南部平野部", 8}},
    {763u, std::string_view{"宮崎県南部山沿い", 8}},
    {770u, std::string_view{"鹿児島県薩摩地方", 8}},
    {771u, std::string_view{"鹿児島県大隅地方", 8}},
    {783u, std::string_view{"五島列島近海", 6}},
    {784u, std::string_view{"天草灘", 3}},
    {785u, std::string_view{"有明海", 3}},
    {786u, std::string_view{"橘湾", 2}},
    {787u, std::string_view{"鹿児島湾", 4}},
    {790u, std::string_view{"種子島近海", 5}},
    {791u, std::string_view{"日向灘", 3}},
    {793u, std::string_view{"奄美大島近海", 6}},
    {795u, std::string_view{"壱岐・対馬近海", 7}},
    {796u, std::string_view{"福岡県北西沖", 6}},
    {797u, std::string_view{"薩摩半島西方沖", 7}},
    {798u, std::string_view{"トカラ列島近海", 7}},
    {799u, std::string_view{"奄美大島北西沖", 7}},
    {820u, std::string_view{"大隅半島東方沖", 7}},
    {821u, std::string_view{"九州地方南東沖", 7}},
    {822u, std::string_view{"種子島南東沖", 6}},
    {823u, std::string_view{"奄美大島北東沖", 7}},
    {850u, std::string_view{"沖縄本島近海", 6}},
    {851u, std::string_view{"南大東島近海", 6}},
    {852u, std::string_view{"沖縄本島南方沖", 7}},
    {853u, std::string_view{"宮古島近海", 5}},
    {854u, std::string_view{"石垣島近海", 5}},
    {855u, std::string_view{"石垣島南方沖", 6}},
    {856u, std::string_view{"西表島付近", 5}},
    {857u, std::string_view{"与那国島近海", 6}},
    {858u, std::string_view{"沖縄本島北西沖", 7}},
    {859u, std::string_view{"宮古島北西沖", 6}},
    {860u, std::string_view{"石垣島北西沖", 6}},
    {900u, std::string_view{"台湾付近", 4}},
    {901u, std::string_view{"東シナ海", 4}},
    {902u, std::string_view{"四国沖", 3}},
    {903u, std::string_view{"鳥島近海", 4}},
    {904u, std::string_view{"鳥島東方沖", 5}},
    {905u, std::string_view{"オホーツク海南部", 8}},
    {906u, std::string_view{"サハリン西方沖", 7}},
    {907u, std::string_view{"日本海北部", 5}},
    {908u, std::string_view{"日本海中部", 5}},
    {909u, std::string_view{"日本海西部", 5}},
    {911u, std::string_view{"父島近海", 4}},
    {912u, std::string_view{"千島列島", 4}},
    {913u, std::string_view{"千島列島南東沖", 7}},
    {914u, std::string_view{"北海道南東沖", 6}},
    {915u, std::string_view{"東北地方東方沖", 7}},
    {916u, std::string_view{"小笠原諸島西方沖", 8}},
    {917u, std::string_view{"硫黄島近海", 5}},
    {918u, std::string_view{"小笠原諸島東方沖", 8}},
    {919u, std::string_view{"南海道南方沖", 6}},
    {920u, std::string_view{"薩南諸島東方沖", 7}},
    {921u, std::string_view{"本州南方沖", 5}},
    {922u, std::string_view{"サハリン南部付近", 8}},
    {930u, std::string_view{"北西太平洋", 5}},
    {932u, std::string_view{"マリアナ諸島", 6}},
    {933u, std::string_view{"黄海", 2}},
    {934u, std::string_view{"朝鮮半島南部", 6}},
    {935u, std::string_view{"朝鮮半島北部", 6}},
    {936u, std::string_view{"中国東北部", 5}},
    {937u, std::string_view{"ウラジオストク付近", 9}},
    {938u, std::string_view{"シベリア南部", 6}},
    {939u, std::string_view{"サハリン近海", 6}},
    {940u, std::string_view{"アリューシャン列島", 9}},
    {941u, std::string_view{"カムチャツカ半島付近", 10}},
    {942u, std::string_view{"北米西部", 4}},
    {943u, std::string_view{"北米中部", 4}},
    {944u, std::string_view{"北米東部", 4}},
    {945u, std::string_view{"中米", 2}},
    {946u, std::string_view{"南米西部", 4}},
    {947u, std::string_view{"南米中部", 4}},
    {948u, std::string_view{"南米東部", 4}},
    {949u, std::string_view{"北東太平洋", 5}},
    {950u, std::string_view{"南太平洋", 4}},
    {951u, std::string_view{"インドシナ半島付近", 9}},
    {952u, std::string_view{"フィリピン付近", 7}},
    {953u, std::string_view{"インドネシア付近", 8}},
    {954u, std::string_view{"グアム付近", 5}},
    {955u, std::string_view{"ニューギニア付近", 8}},
    {956u, std::string_view{"ニュージーランド付近", 10}},
    {957u, std::string_view{"オーストラリア付近", 9}},
    {958u, std::string_view{"シベリア付近", 6}},
    {959u, std::string_view{"ロシア西部", 5}},
    {960u, std::string_view{"ロシア中部", 5}},
    {961u, std::string_view{"ロシア東部", 5}},
    {962u, std::string_view{"中央アジア", 5}},
    {963u, std::string_view{"中国西部", 4}},
    {964u, std::string_view{"中国中部", 4}},
    {965u, std::string_view{"中国東部", 4}},
    {966u, std::string_view{"インド付近", 5}},
    {967u, std::string_view{"インド洋", 4}},
    {968u, std::string_view{"中東", 2}},
    {969u, std::string_view{"ヨーロッパ西部", 7}},
    {970u, std::string_view{"ヨーロッパ中部", 7}},
    {971u, std::string_view{"ヨーロッパ東部", 7}},
    {972u, std::string_view{"地中海", 3}},
    {973u, std::string_view{"アフリカ西部", 6}},
    {974u, std::string_view{"アフリカ中部", 6}},
    {975u, std::string_view{"アフリカ東部", 6}},
    {976u, std::string_view{"北大西洋", 4}},
    {977u, std::string_view{"南大西洋", 4}},
    {978u, std::string_view{"北極付近", 4}},
    {979u, std::string_view{"南極付近", 4}},
    {999u, std::string_view{"遠地", 2}},
    {1000u, std::string_view{"その他の震央地名", 8}},};
[[nodiscard]] inline constexpr std::optional<std::string_view> qzss_dcr_jma_epicenter_and_hypocenter_lookup(uint16_t id) noexcept {
    uint16_t lo = 0, hi = 345;
    while (lo < hi) {
        uint16_t mid = static_cast<uint16_t>(lo + (hi - lo) / 2);
        if (QZSS_DCR_JMA_EPICENTER_AND_HYPOCENTER_TABLE[mid].id == id) return QZSS_DCR_JMA_EPICENTER_AND_HYPOCENTER_TABLE[mid].label;
        if (QZSS_DCR_JMA_EPICENTER_AND_HYPOCENTER_TABLE[mid].id < id) lo = mid + 1;
        else hi = mid;
    }
    return std::nullopt;
}

#else

[[nodiscard]] inline constexpr std::optional<std::string_view> qzss_dcr_jma_epicenter_and_hypocenter_lookup(uint16_t id) noexcept {
    (void)id;
    return std::nullopt;
}

#endif

} // namespace def
} // namespace azaraC
