#pragma once
// AUTO-GENERATED from azarashi 0.16.1 with CI-CD
// Source module : qzss_dcx_camf_a4_hazard_category_and_type
// Variable      : qzss_dcx_camf_a4_hazard_definition
// Entries       : 113
// Strategy      : array

#include <cstdint>
#include <optional>
#include <string_view>
#include "../azaraC.h"

namespace azaraC {
namespace def {

inline constexpr std::optional<std::string_view> QZSS_DCX_CAMF_A4_HAZARD_DEFINITION_TABLE[] = {
    std::string_view{"Attack performed by an aircraft, usually of military type, either by bombing (or similar), firing guns or missiles.", 115},
    std::string_view{"Intentional attempt to expose, alter, disable, destroy, steal or gain unauthorized access to or make unauthorised use of IT equipment.", 134},
    std::string_view{"From www.dhs.gov 'Attack performed with a device producing a nuclear explosion.", 79},
    std::string_view{"Presence of hazardous biological materials that present a risk or potential risk to the health of humans, animals, plants, or the environment.", 142},
    std::string_view{"Presence of hazardous chemical materials that present a risk or potential risk to the health of humans, animals, plants, or the environment.", 140},
    std::string_view{"Presence of hazardous explosive materials that present a risk or potential risk to the health of humans, animals, plants, or the environment.", 141},
    std::string_view{"Meteorite entering from space into the earth atmosphere.", 56},
    std::string_view{"Missile launch.", 15},
    std::string_view{"Presence of hazardous nuclear materials that present a risk or potential risk to the health of humans, animals, plants, or the environment.", 139},
    std::string_view{"Accident occurring at an installation where power is generated by a nuclear reactor.", 84},
    std::string_view{"Presence of hazardous radioactive materials that present a risk or potential risk to the health of humans, animals, plants, or the environment.", 143},
    std::string_view{"Satellite or parts of a satellite or launcher or space vehicle entering or re-entering from space into the earth atmosphere.", 124},
    std::string_view{"Test of a warning device emitting a loud noise.", 47},
    std::string_view{"Rain containing dissolved acidifying compounds, resulting from chemical pollution of the atmosphere by sulphur and nitrogen compounds. When deposited, these increase the acidity of the soil and water causing agricultural and ecological damage.", 243},
    std::string_view{"Precise threshold is according to each local standard.", 54},
    std::string_view{"Drinking water containing contaminants (germs and/or chemicals) above the quality standard. Precise threshold according to each local standard.", 143},
    std::string_view{"Uncontrolled release of natural gas or gaseous product in the environment.", 74},
    std::string_view{"Marine pollution occurs when substances used or spread by humans, such as industrial, agricultural and residential waste, particles, noise, excess carbon dioxide or invasive organisms enter the ocean and cause harmful effects there. Precise threshold is according to each local standard.", 287},
    std::string_view{"Disturbing or unwanted noise that may present a potential risk to the health of humans, animals and wildlife.", 109},
    std::string_view{"Infestation of insects or pervasive influx and development of insects or parasites affecting humans, animals, crops and materials.", 130},
    std::string_view{"Contamination of water in rivers, usually as a result of human activities, in such a manner that negatively affects its legitimate uses.", 136},
    std::string_view{"More general, particulates are microscopic solid particles suspended in the air. The source of the particulate matter can be natural or anthropogenic having adverse effect on human health. The IARC and WHO designate airborne particulates as a Group 1 carcinogen. Particulates are the most harmful form of air pollution due to their ability to penetrate deep into the lungs, blood streams and brain, causing health problems including heart attacks, respiratory disease, and premature death.", 489},
    std::string_view{"Precise threshold is according to each local standard.", 54},
    std::string_view{"A large and destructive fire that threatens human life, health, and/or property.", 80},
    std::string_view{"Operation of firefighters in response to a fire or other emergency report. Note: Definition may vary, depending on the responsibility of the fire brigade in each country.", 170},
    std::string_view{"Potentially dangerous gases emitted from a fire.", 48},
    std::string_view{"A type of wildfire in a wooded area.", 36},
    std::string_view{"An often-noxious suspension of particles in the air.", 52},
    std::string_view{"Prolonged and offensive smell leading to the impairment of human well-being over a certain period of time at regular or irregular intervals.", 140},
    std::string_view{"Increased likelihood of accidental fire.", 40},
    std::string_view{"Fire affecting the structural parts of a building or a fire affecting an industrial site.", 89},
    std::string_view{"Fine (less than 4 mm in diameter) unconsolidated volcanic debris blown into the atmosphere during an eruption; can remain airborne for long periods of time and travel considerable distance from the source.", 205},
    std::string_view{"A large mass of loosened earth material, snow, or ice that slides, flows or falls rapidly down a mountainside under the force of gravity. Snow Avalanche: Rapid downslope movement of a mix of snow and ice. Debris Avalanche: The sudden and very rapid downslope movement of unsorted mass of rock and soil. There are two general types of debris avalanches - a cold debris avalanche usually results from an unstable slope suddenly collapsing whereas a hot debris avalanche results from volcanic activity leading to slope instability and collapse.", 541},
    std::string_view{"Collapse of the land surface due to the dissolving of the subsurface rocks such as limestone or carbonate rock by water.", 120},
    std::string_view{"Types of landslides that occur when heavy rain or rapid snow/ice melt send large amounts of vegetation, mud, or rock downslope by gravitational forces. Includes mud flow, rock fall.", 181},
    std::string_view{"Sudden movement of a block of the Earth’s crust along a geological fault and associated ground shaking.", 105},
    std::string_view{"A type of extra-terrestrial hazard caused by solar wind shockwaves that temporarily disturb the Earth’s magnetosphere. Geomagnetic storms can disrupt power grids, spacecraft operations, and satellite communications.", 217},
    std::string_view{"Ice calving at end of a glacier.", 32},
    std::string_view{"Independent of the presence of water, mass movement may also be triggered by earthquakes.", 89},
    std::string_view{"The ejected magma that moves as a liquid mass downslope from a volcano during an eruption.", 90},
    std::string_view{"Extremely hot gases, ash, and other materials of more than 1,000 ˚C that rapidly flow down the flank of a volcano (more than 700 km/h) during an eruption.", 155},
    std::string_view{"Mass of snow heaped up by the wind and deposited along an obstruction or an irregularity of the terrain.", 104},
    std::string_view{"Shallow water wave caused by the gravitational interactions between the Sun, Moon, and Earth. (from USGS)", 105},
    std::string_view{"A series of waves (with long wavelengths when traveling across the deep ocean) that are generated by a displacement of massive amounts of water through underwater earthquakes, volcanic eruptions or landslides. Tsunami waves travel at very high speed across the ocean but as they begin to reach shallow water they slow down and the wave grows steeper.", 350},
    std::string_view{"(Also known as Lahar) A mud flow resulting from a volcanic event. Hot or cold mixture of earthen material flowing on the slope of a volcano either during or between volcanic eruptions.", 184},
    std::string_view{"A type of volcanic event near an opening/vent in the Earth’s surface including volcanic eruptions of lava, ash, hot vapour, gas, and pyroclastic material.", 156},
    std::string_view{"An abnormal rise in sea level generated by a tropical cyclone or other intense storms.", 86},
    std::string_view{"An epidemic outbreak of disease in an animal population, often with the implication that it may extend to humans.", 113},
    std::string_view{"Presence of unsafe food containing harmful bacteria, viruses, parasites or chemical substances that present a risk to the health of humans, animals, plants or the environment.", 175},
    std::string_view{"Potential source of danger for individual's health.", 51},
    std::string_view{"An epidemic of an infectious disease that has spread across a large region, for instance multiple continents or worldwide, affecting a substantial number of people. A widespread endemic disease with a stable number of infected people is not a pandemic. Widespread endemic diseases with a stable number of infected people such as recurrences of seasonal influenza are generally excluded as they occur simultaneously in large regions of the globe rather than being spread worldwide.", 480},
    std::string_view{"(from GEMET )1) The occurrence of one or more pest species in an area or location where their numbers and impact are currently or potentially at intolerable levels. 2) A sudden increase in destructiveness or population numbers of a pest species in a given area.", 261},
    std::string_view{"Present of infectious agent(s) that present a risk or potential risk to the health of humans, animals, plants, or the environment.", 130},
    std::string_view{"Sudden failure of the building structure resulting in its partial or total destruction.", 87},
    std::string_view{"Interruption or failure of emergency number service.", 52},
    std::string_view{"Interruption or failure of gas supply service.", 46},
    std::string_view{"Interruption or failure of IT systems services.", 47},
    std::string_view{"Interruption or failure of electricity distribution service.", 60},
    std::string_view{"Release in the environment of untreated wastewater.", 51},
    std::string_view{"Interruption or failure of telephone service.", 45},
    std::string_view{"WMO definition: (1) Thin, new ice on freshwater or saltwater, appearing dark in colour because of its transparency, which is a result of its columnar grain structure. On lakes, black ice is commonly overlain by white ice formed from refrozen snow or slush. (2) A popular alternative for glaze. A thin sheet of ice, relatively dark in appearance, may form when light rain or drizzle falls on a road surface that is at a temperature below 0 °C or, alternatively, when water already on the road surface subsequently freezes when the temperature thereof falls below freezing point. It may also be formed when supercooled fog droplets are intercepted by buildings, fences and vegetation.", 683},
    std::string_view{"Occurs when dry and low-lying land is submerged by seawater.", 60},
    std::string_view{"Extreme cold and low temperatures.", 34},
    std::string_view{"Widespread and usually fast-moving windstorms associated with convection/convective storm. Derechos include downburst and straight-line winds. The damage from derechos is often confused with the damage from tornadoes.", 217},
    std::string_view{"An extended period of unusually low precipitation that produces a shortage of water for people, animals and plants. Drought is different from most other hazards in that it develops slowly, sometimes even over years, and its onset is generally difficult to detect.", 263},
    std::string_view{"Strong winds carry particles of sand aloft, but generally confined to less than 50 feet (15 m), especially common in arid and semi-arid environments. A dust storm is also characterised by strong winds but carries smaller particles of dust rather than sand over an extensive area.", 279},
    std::string_view{"Floating ice in rivers or icebergs in the open sea.", 51},
    std::string_view{"A general term for the overflow of water from a stream channel onto normally dry land in the floodplain (riverine flooding), higher-than normal levels along the coast and in lakes or reservoirs (coastal flooding) as well as ponding of water at or near the point where the rain fell (flash floods).", 297},
    std::string_view{"A suspension of very small, usually microscopic water droplets in the air, reducing visibility at the Earth’s surface.", 120},
    std::string_view{"Solid precipitation in the form of irregular pellets or balls of ice more than 5 mm in diameter.", 96},
    std::string_view{"A general term for temperature variations above (extreme heat).", 63},
    std::string_view{"A high-voltage, visible electrical discharge produced by a thunderstorm and followed by the sound of thunder.", 109},
    std::string_view{"Pollens that can cause human allergies are those of anemophilous plants (pollen is dispersed by air currents.) Such plants produce large quantities of lightweight pollen (because wind dispersal is random and the likelihood of one pollen grain landing on another flower is small), which can be carried for great distances and are easily inhaled by humans.", 354},
    std::string_view{"Rainfall greater than or equal to 50 mm in past 24 hours. Note: Precise threshold is according to each local standard.", 118},
    std::string_view{"A low-pressure system in winter months with significant accumulations of snow, freezing rain, sleet or ice. A blizzard is a severe snowstorm with winds exceeding 35 mph (56 km/h) for three or more hours, producing reduced visibility (less than .25 mile (400 m).", 261},
    std::string_view{"Snowfall greater than or equal to 50 mm in past 24 hours. Note: Precise threshold is according to each local standard.", 118},
    std::string_view{"Meteorological event generating winds equal or higher than 10 on the Beaufort scale.", 84},
    std::string_view{"Gradual warning causing ground ice to degrade, potentially leading the soil surface to collapse.", 96},
    std::string_view{"A violently rotating column of air that reaches the ground or open water (waterspout).", 86},
    std::string_view{"A tropical cyclone originates over tropical or subtropical waters. It is characterised by a warm-core, non-frontal synoptic-scale cyclone with a low-pressure centre, spiral rain bands and strong winds. Depending on their location, tropical cyclones are referred to as hurricanes (Atlantic, Northeast Pacific), typhoons (Northwest Pacific), or cyclones (South Pacific and Indian Ocean). With a minimum wind speed of 119 km/h (or 74 miles/h) a tropical storm in the Atlantic or Northeast Pacific is called a hurricane.", 516},
    std::string_view{"Frost is the consequence of radiative cooling resulting in the formation of thin ice crystals on the ground or other surfaces in the form of needles, feathers, scales, or fans. Frost occurs when the temperature of surfaces is below freezing and water vapor from humid air forms solid deposits on the cold surface. Freeze occurs when the air temperature is at (32 °F / 0 °C) or below over a widespread area for a climatologically significant period of time. Use of the term is usually restricted to advective situations or to occasions when wind or other conditions prevent frost. Frost and freeze are particularly damaging during the crop growing season.", 656},
    std::string_view{"A tropical cyclone originates over tropical or subtropical waters. It is characterised by a warm-core, non-frontal synoptic-scale cyclone with a low-pressure centre, spiral rain bands and strong winds. Depending on their location, tropical cyclones are referred to as hurricanes (Atlantic, Northeast Pacific), typhoons (Northwest Pacific), or cyclones (South Pacific and Indian Ocean). With a minimum wind speed of 119 km/h (or 74 miles/h) a tropical storm in the Atlantic or Northeast Pacific is called a hurricane.", 516},
    std::string_view{"Incident at a dam potentially leading to the uncontrolled release of the dam content.", 85},
    std::string_view{"Incident at a dike potentially leading to the uncontrolled release of water.", 76},
    std::string_view{"Activity to render safe all types of ordnance, including explosive, chemical and biological. It covers land and underwater location, identification, render-safe, and recovery (or disposal) of ordnance.", 201},
    std::string_view{"Incident at an industrial site affecting the surrounding area.", 62},
    std::string_view{"Any of the dangers peculiar to the winning and working of coal and minerals. These include collapse of ground, explosion of released gas, inundation by water, spontaneous combustion, inhalation of dust and poisonous gases, etc.", 227},
    std::string_view{"Unexpected presence of bomb or ammunition.", 42},
    std::string_view{"A march or gathering of people taking part in to show their opposition to something or their support for something.", 115},
    std::string_view{"An unexpected uncontrolled release of substances that have the potential to harm a person or the environment upon contact.", 122},
    std::string_view{"Emergency situation that requires immediate intervention to save the life of the persons concerned.", 99},
    std::string_view{"Planned happening which may generate significant disruption in road traffic or transport.", 89},
    std::string_view{"Unaccounted person whose health status (alive/dead) cannot be confirmed.", 72},
    std::string_view{"Intentional use of explosive materials aiming at killing or damaging the health of humans, animals, plants, or the environment.", 127},
    std::string_view{"Announcement of a potentially dangerous situation or event to the public impacting their safety.", 96},
    std::string_view{"Presence of an unidentified flying object which may present a risk or potential risk to the health of humans, animals, plants, or the environment.", 146},
    std::string_view{"Presence of an unidentified animal which may present a risk or a potential risk to the health of humans, animals, plants, or the environment.", 141},
    std::string_view{"Intentional use of dangerous chemical materials aiming at killing or damaging the health of humans, animals, plants, or the environment.", 136},
    std::string_view{"Paramilitary armed forces carrying violent actions.", 51},
    std::string_view{"Airplane or other vehicle under the control of hijackers.", 57},
    std::string_view{"Dangerous use of firearm(s) or weapons in a populated area.", 59},
    std::string_view{"Military armed forces carrying violent actions.", 47},
    std::string_view{"Terrorist action aiming at generating a high number of victims or major material damage.", 88},
    std::string_view{"Aircraft crash.", 15},
    std::string_view{"Structural failure of a bridge resulting in its partial or total destruction.", 77},
    std::string_view{"Accident occurrence associated with and related to the conveyance of dangerous goods by air, road, inland waterways and sea, which results in fatal or serious injury to a person or major damage to property or environment.", 221},
    std::string_view{"Ship accident on an inland waterway.", 36},
    std::string_view{"Sinking ship or any other event occurring at sea which may present of security or safety risk.", 94},
    std::string_view{"Leak of oil or pollutant from a ship or other transportation mean resulting in pollution.", 89},
    std::string_view{"Announcement of road traffic disruption.", 40},
    std::string_view{"Accident occurring on a railway and involving train(s) and/or other vehicles.", 77},
    std::string_view{"Car crash or railway accident occurring in a tunnel.", 52},
    std::string_view{"Test alert message for end-to-end testing.", 42}
};
inline constexpr uint8_t QZSS_DCX_CAMF_A4_HAZARD_DEFINITION_BASE = 1;
inline constexpr uint8_t QZSS_DCX_CAMF_A4_HAZARD_DEFINITION_SIZE = 113;
[[nodiscard]] inline constexpr std::optional<std::string_view> qzss_dcx_camf_a4_hazard_definition_lookup(uint8_t id) {
    if (id < QZSS_DCX_CAMF_A4_HAZARD_DEFINITION_BASE || id >= QZSS_DCX_CAMF_A4_HAZARD_DEFINITION_BASE + QZSS_DCX_CAMF_A4_HAZARD_DEFINITION_SIZE) return std::nullopt;
    return QZSS_DCX_CAMF_A4_HAZARD_DEFINITION_TABLE[id - QZSS_DCX_CAMF_A4_HAZARD_DEFINITION_BASE];
}

} // namespace def
} // namespace azaraC
