#pragma once
// AUTO-GENERATED from azarashi 0.16.1 with CI-CD
// Source module : qzss_dcx_camf_a4_hazard_category_and_type
// Variable      : qzss_dcx_camf_a4_hazard_category
// Entries       : 113
// Strategy      : array

#include <cstdint>
#include <optional>
#include <string_view>

namespace azaraC {
namespace def {

inline constexpr std::optional<std::string_view> QZSS_DCX_CAMF_A4_HAZARD_CATEGORY_TABLE[] = {
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"CBRNE", 5},
    std::string_view{"ENVIRONMENT", 11},
    std::string_view{"ENVIRONMENT", 11},
    std::string_view{"ENVIRONMENT", 11},
    std::string_view{"ENVIRONMENT", 11},
    std::string_view{"ENVIRONMENT", 11},
    std::string_view{"ENVIRONMENT", 11},
    std::string_view{"ENVIRONMENT", 11},
    std::string_view{"ENVIRONMENT", 11},
    std::string_view{"ENVIRONMENT", 11},
    std::string_view{"ENVIRONMENT", 11},
    std::string_view{"FIRE", 4},
    std::string_view{"FIRE", 4},
    std::string_view{"FIRE", 4},
    std::string_view{"FIRE", 4},
    std::string_view{"FIRE", 4},
    std::string_view{"FIRE", 4},
    std::string_view{"FIRE", 4},
    std::string_view{"FIRE", 4},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"GEO", 3},
    std::string_view{"HEALTH", 6},
    std::string_view{"HEALTH", 6},
    std::string_view{"HEALTH", 6},
    std::string_view{"HEALTH", 6},
    std::string_view{"HEALTH", 6},
    std::string_view{"HEALTH", 6},
    std::string_view{"INFRASTRUCTURE", 14},
    std::string_view{"INFRASTRUCTURE", 14},
    std::string_view{"INFRASTRUCTURE", 14},
    std::string_view{"INFRASTRUCTURE", 14},
    std::string_view{"INFRASTRUCTURE", 14},
    std::string_view{"INFRASTRUCTURE", 14},
    std::string_view{"INFRASTRUCTURE", 14},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"MET", 3},
    std::string_view{"RESCUE", 6},
    std::string_view{"RESCUE", 6},
    std::string_view{"RESCUE", 6},
    std::string_view{"RESCUE", 6},
    std::string_view{"RESCUE", 6},
    std::string_view{"SAFETY", 6},
    std::string_view{"SAFETY", 6},
    std::string_view{"SAFETY", 6},
    std::string_view{"SAFETY", 6},
    std::string_view{"SAFETY", 6},
    std::string_view{"SAFETY", 6},
    std::string_view{"SAFETY", 6},
    std::string_view{"SAFETY", 6},
    std::string_view{"SAFETY", 6},
    std::string_view{"SAFETY", 6},
    std::string_view{"SECURITY", 8},
    std::string_view{"SECURITY", 8},
    std::string_view{"SECURITY", 8},
    std::string_view{"SECURITY", 8},
    std::string_view{"SECURITY", 8},
    std::string_view{"SECURITY", 8},
    std::string_view{"TRANSPORT", 9},
    std::string_view{"TRANSPORT", 9},
    std::string_view{"TRANSPORT", 9},
    std::string_view{"TRANSPORT", 9},
    std::string_view{"TRANSPORT", 9},
    std::string_view{"TRANSPORT", 9},
    std::string_view{"TRANSPORT", 9},
    std::string_view{"TRANSPORT", 9},
    std::string_view{"TRANSPORT", 9},
    std::string_view{"OTHER", 5}
};
inline constexpr uint8_t QZSS_DCX_CAMF_A4_HAZARD_CATEGORY_BASE = 1;
inline constexpr uint8_t QZSS_DCX_CAMF_A4_HAZARD_CATEGORY_SIZE = 113;
[[nodiscard]] inline constexpr std::optional<std::string_view> qzss_dcx_camf_a4_hazard_category_lookup(uint8_t id) {
    if (id < QZSS_DCX_CAMF_A4_HAZARD_CATEGORY_BASE || id >= QZSS_DCX_CAMF_A4_HAZARD_CATEGORY_BASE + QZSS_DCX_CAMF_A4_HAZARD_CATEGORY_SIZE) return std::nullopt;
    return QZSS_DCX_CAMF_A4_HAZARD_CATEGORY_TABLE[id - QZSS_DCX_CAMF_A4_HAZARD_CATEGORY_BASE];
}

} // namespace def
} // namespace azaraC
